---
title: "Bayesian Statistics"
subtitle: "Ph.D. in Economics, Statistics, and Data Science - University of Milano-Bicocca"
author:
  name: Raffaele Argiento, Bernardo Nipoti, and Tommaso Rigon
  affiliation: DEMS
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    code-line-numbers: true
    smooth-scroll: true
    execute:
      echo: true
      message: false
      warning: false
editor_options: 
  chunk_output_type: console
---

Bayesian Statistics is a Ph.D. course organized in **three modules**, which are:

- Introduction to Bayesian statistics (15h)  -- Bernardo Nipoti
- [Bayesian computations](https://tommasorigon.github.io/CompStat/)  (15h) -- Tommaso Rigon
- Bayesian modelling (xx h) -- Raffaele Argiento

<!-- ## Prerequisites -->

<!-- It is assumed the knowledge of the following topics: -->

<!--   * Fundamentals of Bayesian statistics. Refer to Chapters 1-5 of Hoff (2009). -->
<!--   * Monte Carlo integration. Refer to Chapter 3 of Robert and Casella (2009), or Chapter 4 of Hoff (2009). -->

<!--    Further preliminary material is available (in Italian) at the website of the course [R for the multivariate statistical analysis](https://tommasorigon.github.io/introR/).  -->

## Detailed syllabus

**Principles of Bayesian statistics** (Bernardo Nipoti, 15h)

-	Exchangeability and de Finetti’s theorem
-	The Bayesian framework
-	Conjugate prior distributions
-	Bayesian point estimation
-	Test and credible intervals
-	The normal model
-	The multivariate normal model
-	Introduction to hierarchical modelling

---------------------------------------------------

**Bayesian computations** (Tommaso Rigon, 15h)

- Metropolis-Hastings and Gibbs sampling 
- Optimal scaling & adaptive Metropolis 
- MALA algorithm & Hamiltonian Monte Carlo 
- Missing data problems, Gibbs sampling and the EM algorithm 
- Laplace appr., Variational Bayes, and Expectation Propagation

---------------------------------------------------

**Advanced Bayesian modelling** (Raffaele Argiento, 15h)

## Exam

The exam rules are described [here](exam_rules.pdf). In short, you will be asked to read a paper, write a short review, and then make a presentation. Here is an example from previous years:

1. [Paper](AOAP2018.pdf) assigned to a PhD student, using the keyword system;
1. [Short review](ghilotti_review.pdf), written using the *Bayesian Analysis* template;
1. [Slides](ghilotti_slides.pdf) of the presentation.

## References

#### Books

 - Hoff, P. D. (2009). _A First Course in Bayesian Statistical Methods_. Springer.
 - Robert, C. P., and Casella, G. (2009). [_Introducing Monte Carlo methods with R_](https://link.springer.com/content/pdf/10.1007%2F978-1-4419-1576-4.pdf). Springer.
 -	Robert, C., 2007. _The Bayesian choice: from decision-theoretic foundations to computational implementation_. Springer Science & Business Media.
-	Gelman, A., Carlin, J.B., Stern, H.S., Dunson, D.B., Vehtari, A. and Rubin, D.B., 2013. [_Bayesian data analysis_](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf). CRC press.

 

#### Articles

1. Blei, D. M., Kucukelbirb A., and McAuliffe, J. D. (2017). Variational inference: a review for statisticians. *Journal of the American Statistical Association*, **112**(518), 859--877.

1. Roberts, G. O. and Rosenthal, J. S. (2001). Optimal scaling for various Metropolis-Hastings algorithms. *Statistical Science*, **16**(4), 351--367.


------------------------------------------------

